---
name: Build documentation

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/build-documentation.yaml'
    - '.github/mkdocs/**'
    - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@a31c6b13a80e4a4fbb525eeb7a2a78253bb15fa5 # master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: .github/mkdocs/mkdocs.yaml
        REQUIREMENTS: .github/mkdocs/requirements.txt
