---
name: Build documentation

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/build-documentation.yaml'
    - '.github/mkdocs/**'
    - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v5

    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: .github/mkdocs/mkdocs.yaml
        REQUIREMENTS: .github/mkdocs/requirements.txt
